### ISSUE TITLE
crash `error:0308010C:digital envelope routines::unsupported`

### ISSUE THREAD

**Issue by Arondight** [icqqjs/icqq#28]
### Node.js Version

v18.14.2

### Package(icqq) Version

0.3.2

### Login Protocol

iPad

### Bug Description (最好截图说明，你的文字描述可能无法准确传达信息)

感觉不应该崩溃，直接提交到这儿让作者看看，溜了

### Log Details (控制台日志，请提供包含前后一段时间内的)

```
1|bot      | [2023-05-07T17:43:14.252] [ERROR] [icqq] - 旧版token于当前版本不兼容，请手动删除token后重新运行
1|bot      | [2023-05-07T17:43:14.252] [WARN] [icqq] - 若非无法登录，请勿随意升级版本
1|bot      | [2023-05-07T17:43:14.257] [DEBUG] [icqq] - send:wtlogin.exchange_emp seq:551
1|bot      | [2023-05-07T17:43:14.360] [MARK] [icqq] - 120.241.150.69:8080 connected
1|bot      | [2023-05-07T17:43:14.360] [DEBUG] [icqq] - send:Client.CorrectTime seq:552
1|bot      | [2023-05-07T17:43:14.422] [DEBUG] [icqq] - recv:Client.CorrectTime seq:552
1|bot      | [2023-05-07T17:43:14.454] [DEBUG] [icqq] - recv:wtlogin.exchange_emp seq:551
1|bot      | [2023-05-07T17:43:14.455] [MARK] [icqq] - 登录token过期
1|bot      | [2023-05-07T17:43:14.456] [MARK] [icqq] - 3秒后重新连接

1|bot  | [2023-05-07T17:43:17.832] [INFO] [icqq] - Calculating PoW of plus 10000 times cost 106 ms
1|bot  | node:internal/crypto/cipher:122
1|bot  |     this[kHandle].initiv(cipher, credential, iv, authTagLength);
1|bot  |                   ^
1|bot  | Error: error:0308010C:digital envelope routines::unsupported
1|bot  |     at Cipheriv.createCipherBase (node:internal/crypto/cipher:122:19)
1|bot  |     at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:141:3)
1|bot  |     at new Cipheriv (node:internal/crypto/cipher:249:3)
1|bot  |     at Object.createCipheriv (node:crypto:141:10)
1|bot  |     at sign (/opt/apps/Adachi-BOT/node_modules/icqq/lib/internal/enctyption.js:465:27)
1|bot  |     at 1348 (/opt/apps/Adachi-BOT/node_modules/icqq/lib/core/tlv.js:400:72)
1|bot  |     at Client.packTlv (/opt/apps/Adachi-BOT/node_modules/icqq/lib/core/tlv.js:37:24)
1|bot  |     at Client.passwordLogin (/opt/apps/Adachi-BOT/node_modules/icqq/lib/core/base-client.js:382:31)
1|bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|bot  |     at async Client.login (/opt/apps/Adachi-BOT/node_modules/icqq/lib/client.js:210:24) {
1|bot  |   library: 'digital envelope routines',
1|bot  |   reason: 'unsupported',
1|bot  |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
1|bot  | }
1|bot  | Node.js v18.14.2
```

**Comment by Arondight** [comment]
嗯这应该是个 bug 了，起不来了

**Comment by TakeNAKE** [comment]
linux使用
export NODE_OPTIONS='--openssl-legacy-provider'
创造环境变量
windows使用
SET NODE_OPTIONS=--openssl-legacy-provider

**Comment by Arondight** [comment]
> --openssl-legacy-provider

牛

**Comment by Arondight** [comment]
> 创造环境变量

不用搞得这么麻烦参数中简单加个选项就可以

https://github.com/Arondight/Adachi-BOT/commit/38f3756b9eff64dc77dd328897b01d759a425650

**Comment by 1161476521** [comment]
> 

加在哪里，求大佬指点

**Comment by Arondight** [comment]
新版本已经通过内置实现解决了这个错误，issue closed
